### ISSUE TITLE
initWithBase64EncodedString missing =

### ISSUE THREAD

**Issue by xuaninbox** [dashevo/TinyCborObjc#9]
the base64String missing = at the end causing

https://github.com/dashevo/TinyCborObjc/blob/ad7ab1f3eebab4fc99dc4897e2e85f9960a3df20/TinyCborObjc/NSData%2BDSCborDecoding.m#L117

always return nil.

https://github.com/dashevo/TinyCborObjc/blob/ad7ab1f3eebab4fc99dc4897e2e85f9960a3df20/TinyCborObjc/cbortojson_nsstring.m#L536

I changed this to @"\"%@%s=\"" for it to work.

**Comment by podkovyrin** [comment]
Can you provide more details on this and an example of data to decode, please?
I tried your suggestion but tests started to fail. For instance, string `YWJj=` is decoded to nil by `[[NSData alloc] initWithBase64EncodedString:base64String options:kNilOptions]` method. However `YWJj` correctly decodes to `abc`.

**Comment by hamchapman** [comment]
I think this can be closed after #12 was merged 👍
